"""add_base_qty_base_uom_multiplier_fields_to_bom_item_for_standardized_calculation

Revision ID: 439abd559f51
Revises: 6b8fbc359267
Create Date: 2025-08-24 20:06:15.794326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439abd559f51'
down_revision = '6b8fbc359267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_bom_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplier', sa.Numeric(precision=12, scale=6), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_bom_items', schema=None) as batch_op:
        batch_op.drop_column('multiplier')

    # ### end Alembic commands ###
