"""x2

Revision ID: 47a8d44d9b24
Revises: 7be374231096
Create Date: 2025-09-10 20:11:10.966383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a8d44d9b24'
down_revision = '7be374231096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_internal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('int_part_num', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['gj_users.id'], name=op.f('fk_gj_internal_products_created_by_id_gj_users')),
    sa.ForeignKeyConstraint(['plant_id'], ['gj_plants.id'], name=op.f('fk_gj_internal_products_plant_id_gj_plants')),
    sa.ForeignKeyConstraint(['product_id'], ['gj_products.id'], name=op.f('fk_gj_internal_products_product_id_gj_products')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['gj_users.id'], name=op.f('fk_gj_internal_products_updated_by_id_gj_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_internal_products'))
    )
    with op.batch_alter_table('gj_internal_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gj_internal_products_int_part_num'), ['int_part_num'], unique=False)

    with op.batch_alter_table('gj_routings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('int_product_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_gj_routings_plant_id_gj_plants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_gj_routings_int_product_id_gj_internal_products'), 'gj_internal_products', ['int_product_id'], ['id'])
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_routings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_gj_routings_int_product_id_gj_internal_products'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_gj_routings_plant_id_gj_plants'), 'gj_plants', ['plant_id'], ['id'])
        batch_op.drop_column('int_product_id')

    with op.batch_alter_table('gj_internal_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gj_internal_products_int_part_num'))

    op.drop_table('gj_internal_products')
    # ### end Alembic commands ###
