"""change product

Revision ID: 5e0bdfa2bf30
Revises: 7b479384c192
Create Date: 2025-09-07 21:01:09.106158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0bdfa2bf30'
down_revision = '7b479384c192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_products', schema=None) as batch_op:
        batch_op.drop_column('cust_ver')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_ver', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
