"""hh

Revision ID: 6146fb9e3d3e
Revises: 47a8d44d9b24
Create Date: 2025-09-11 06:55:56.164453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6146fb9e3d3e'
down_revision = '47a8d44d9b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_routings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gj_routings_int_part_num'))
        batch_op.drop_constraint(batch_op.f('fk_gj_routings_product_id_gj_products'), type_='foreignkey')
        batch_op.drop_column('int_part_num')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_routings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('int_part_num', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_gj_routings_product_id_gj_products'), 'gj_products', ['product_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_gj_routings_int_part_num'), ['int_part_num'], unique=False)

    # ### end Alembic commands ###
