"""add_raw_time_fields_to_operation_resource

Revision ID: 6b8fbc359267
Revises: c9a426b0d0b7
Create Date: 2025-08-24 19:28:06.027065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8fbc359267'
down_revision = 'c9a426b0d0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_operation_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_run_time_val', sa.Numeric(precision=12, scale=6), nullable=True))
        batch_op.add_column(sa.Column('raw_run_time_uom', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('items_per_raw_uom', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_operation_resources', schema=None) as batch_op:
        batch_op.drop_column('items_per_raw_uom')
        batch_op.drop_column('raw_run_time_uom')
        batch_op.drop_column('raw_run_time_val')

    # ### end Alembic commands ###
