"""Add supplier relationship model

Revision ID: 94843ddc7402
Revises: 04d1869a39bd
Create Date: 2025-08-11 22:42:00.217676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94843ddc7402'
down_revision = '04d1869a39bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_supplier_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('sup_loc_id', sa.Integer(), nullable=False),
    sa.Column('supplier_part_num', sa.String(length=100), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['gj_users.id'], name=op.f('fk_gj_supplier_relationships_created_by_id_gj_users')),
    sa.ForeignKeyConstraint(['material_id'], ['gj_materials.id'], name=op.f('fk_gj_supplier_relationships_material_id_gj_materials')),
    sa.ForeignKeyConstraint(['sup_loc_id'], ['gj_supplier_locations.id'], name=op.f('fk_gj_supplier_relationships_sup_loc_id_gj_supplier_locations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['gj_users.id'], name=op.f('fk_gj_supplier_relationships_updated_by_id_gj_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_supplier_relationships')),
    sa.UniqueConstraint('material_id', 'sup_loc_id', name='uq_material_supplier_loc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gj_supplier_relationships')
    # ### end Alembic commands ###
