"""Add end_cust_id to Product

Revision ID: 9ff519617961
Revises: c02224004aa1
Create Date: 2025-08-25 22:30:51.388584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff519617961'
down_revision = 'c02224004aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_cust_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_gj_products_end_cust_id_gj_customers'), 'gj_customers', ['end_cust_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gj_products_end_cust_id_gj_customers'), type_='foreignkey')
        batch_op.drop_column('end_cust_id')

    # ### end Alembic commands ###
