"""add_procurement_fields_to_material_supplier

Revision ID: c02224004aa1
Revises: 439abd559f51
Create Date: 2025-08-24 20:11:59.379940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02224004aa1'
down_revision = '439abd559f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_material_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_time_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=12, scale=6), nullable=True))
        batch_op.add_column(sa.Column('min_order_qty', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_material_suppliers', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('min_order_qty')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('lead_time_days')

    # ### end Alembic commands ###
