"""Initial database schema

Revision ID: f16a8a6ee179
Revises: 
Create Date: 2025-08-07 21:07:39.819962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16a8a6ee179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_business_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_business_units')),
    sa.UniqueConstraint('name', name=op.f('uq_gj_business_units_name'))
    )
    op.create_table('gj_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_gj_permissions_name'))
    )
    op.create_table('gj_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_plants')),
    sa.UniqueConstraint('name', name=op.f('uq_gj_plants_name'))
    )
    op.create_table('gj_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_gj_roles_name'))
    )
    op.create_table('gj_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_users')),
    sa.UniqueConstraint('email', name=op.f('uq_gj_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_gj_users_username'))
    )
    op.create_table('gj_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('required_permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['gj_menus.id'], name=op.f('fk_gj_menus_parent_id_gj_menus')),
    sa.ForeignKeyConstraint(['required_permission_id'], ['gj_permissions.id'], name=op.f('fk_gj_menus_required_permission_id_gj_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_menus'))
    )
    op.create_table('gj_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['gj_users.id'], name=op.f('fk_gj_role_permissions_created_by_id_gj_users')),
    sa.ForeignKeyConstraint(['permission_id'], ['gj_permissions.id'], name=op.f('fk_gj_role_permissions_permission_id_gj_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['gj_roles.id'], name=op.f('fk_gj_role_permissions_role_id_gj_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('gj_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('bu_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bu_id'], ['gj_business_units.id'], name=op.f('fk_gj_user_roles_bu_id_gj_business_units')),
    sa.ForeignKeyConstraint(['created_by_id'], ['gj_users.id'], name=op.f('fk_gj_user_roles_created_by_id_gj_users')),
    sa.ForeignKeyConstraint(['plant_id'], ['gj_plants.id'], name=op.f('fk_gj_user_roles_plant_id_gj_plants')),
    sa.ForeignKeyConstraint(['role_id'], ['gj_roles.id'], name=op.f('fk_gj_user_roles_role_id_gj_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['gj_users.id'], name=op.f('fk_gj_user_roles_user_id_gj_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gj_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'plant_id', 'bu_id', name='uq_user_role_scope')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gj_user_roles')
    op.drop_table('gj_role_permissions')
    op.drop_table('gj_menus')
    op.drop_table('gj_users')
    op.drop_table('gj_roles')
    op.drop_table('gj_plants')
    op.drop_table('gj_permissions')
    op.drop_table('gj_business_units')
    # ### end Alembic commands ###
